E-Books/Controllers/AccountsController.cs
using E_Books.Data;
using E_Books.Data.Static;
using E_Books.Data.ViewModels;
using E_Books.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace E_Books.Controllers
{
    public class AccountsController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly AppDbContext _context;
        public AccountsController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager, AppDbContext context)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _context = context;
        }

        public IActionResult Login()
        {
            return View(new LoginVM());
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginVM loginVM)
        {
            if (!ModelState.IsValid)
                return View(loginVM);

            var user = await _userManager.FindByEmailAsync(loginVM.EmailAddress);
            if (user != null)
            {
                var passwordCheck = await _userManager.CheckPasswordAsync(user, loginVM.Password);
                if (passwordCheck)
                {
                    var result = await _signInManager.PasswordSignInAsync(user, loginVM.Password, false, false);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index", "Books");
                    }
                }
                else
                {
                    TempData["Error"] = "Wrong Credintials...";
                    return View(loginVM);
                }
            }
            TempData["Error"] = "Wrong credintals try again...!";
            return View(loginVM);
        }

        public IActionResult Signup()
        {
            return View(new SignupVM());
        }

        [HttpPost]
        public async Task<IActionResult> Signup(SignupVM signupVM)
        {
            if (!ModelState.IsValid)
                return View(signupVM);

            var existingUser = await _userManager.FindByEmailAsync(signupVM.EmailAddress);
            if (existingUser != null)
            {
                TempData["Error"] = "Email already in use!";
                return View(signupVM);
            }

            var newUser = new AppUser()
            {
                FullName = signupVM.FullName,
                Email = signupVM.EmailAddress,
                UserName = signupVM.EmailAddress
            };

            var newResponse = await _userManager.CreateAsync(newUser, signupVM.Password);

            if (newResponse.Succeeded)
                await _userManager.AddToRoleAsync(newUser, UserRoles.User);

            return View("RegisterCompleted");
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Books");
        }

        public async Task<IActionResult> Details()
        {
            var loggedInUser = await _userManager.GetUserAsync(HttpContext.User);
            if (loggedInUser is null)
                return View("NotFound");

            SignupVM thisUser = new SignupVM()
            {
                FullName = loggedInUser.FullName,
                EmailAddress = loggedInUser.Email,
            };

            return View(thisUser);
        }

        public async Task<IActionResult> getAllUsers()
        {
            var allUsers = await _userManager.Users.ToListAsync();
            return View(allUsers);
        }
    }
}

E-Books/Controllers/AuthorsController.cs
using E_Books.Data.Services;
using E_Books.Models;
using Microsoft.AspNetCore.Mvc;

namespace E_Books.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly IAuthorsServices _service;
        public AuthorsController(IAuthorsServices service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index(int? pageNumber)
        {
            int pageSize = 5;
            var authors = await _service.GetPageAsync(pageNumber ?? 1, pageSize);
            ViewData["TotalPages"] = await _service.TotalPages(pageSize);
            ViewData["PageIndex"] = pageNumber ?? 1;
            return View(authors);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name,Age,Biography,ProfileURL")] Author author)
        {
            if(!ModelState.IsValid)
                return View(author);
            await _service.AddAsync(author);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int Id)
        {
            var author = await _service.GetByIdAsync(Id);
            if (author == null)
                return View("NotFound");
            return View(author);
        }

        public async Task<IActionResult> Edit(int Id)
        {
            var author_for_edit = await _service.GetByIdAsync(Id);
            if (author_for_edit == null)
                return View("NotFound");

            return View(author_for_edit);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int Id, [Bind("Id,Name,Age,Biography,ProfileURL")]Author newAuthor)
        {
            if (!ModelState.IsValid)
                return View(newAuthor);
            await _service.UpdateAsync(Id, newAuthor);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var author_to_delete = await _service.GetByIdAsync(Id);
            if (author_to_delete == null)
                return View("NotFound");
            return View(author_to_delete);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int Id)
        {
            var author_to_delete = await _service.GetByIdAsync(Id);
            if (author_to_delete == null)
                return View("NotFound");

            await _service.DeleteAsync(Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

E-Books/Controllers/BooksController.cs
using E_Books.Data.Services;
using E_Books.Data.ViewModels;
using E_Books.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.IdentityModel.Tokens;

namespace E_Books.Controllers
{
    public class BooksController : Controller
    {
        private readonly IBooksServices _service;
        public BooksController(IBooksServices service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index(int? pageNumber)
        {
            int pageSize = 12;
            var books = await _service.GetPageAsync(pageNumber ?? 1, pageSize);
            ViewData["TotalPages"] = await _service.TotalPages(pageSize);
            ViewData["PageIndex"] = pageNumber ?? 1;
            return View(books);
        }

        public async Task<IActionResult> Search(string searchString)
        {
            if (string.IsNullOrEmpty(searchString))
                return RedirectToAction(nameof(Index));
            var result = await _service.SearchAsync(searchString);
            if (result.IsNullOrEmpty())
                return View("NotFound");
            return View(result);
        }

        public async Task<IActionResult> Details(int Id)
        {
            var book = await _service.GetBookById(Id);
            if (book == null)
                return View("NotFound");
            return View(book);
        }

        public async Task<IActionResult> Create()
        {
            var bookDropDownData = await _service.GetNewBookDropdownVals();
            ViewBag.PublisherId = new SelectList(bookDropDownData.Publishers, "Id", "Name");
            ViewBag.AuthorIds = new SelectList(bookDropDownData.Authors, "Id", "Name");
            ViewBag.BookStoreIds = new SelectList(bookDropDownData.BookStores, "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewBookVM book)
        {
            if (!ModelState.IsValid)
            {
                var bookDropDownData = await _service.GetNewBookDropdownVals();
                ViewBag.PublisherId = new SelectList(bookDropDownData.Publishers, "Id", "Name");
                ViewBag.AuthorIds = new SelectList(bookDropDownData.Authors, "Id", "Name");
                ViewBag.BookStoreIds = new SelectList(bookDropDownData.BookStores, "Id", "Name");
                return View(book);
            }
            await _service.AddNewBook(book);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int Id)
        {
            var bookDetails = await _service.GetBookById(Id);

            if (bookDetails == null)
                return View("NotFound");

            var response = new NewBookVM()
            {
                Id = bookDetails.Id,
                Title = bookDetails.Title,
                PublishDate = bookDetails.PublishDate,
                Price = bookDetails.Price,
                Summary = bookDetails.Summary,
                BookCover = bookDetails.BookCover,
                Genre = bookDetails.Genre,
                AuthorIds = bookDetails.Authors_Books.Select(n => n.AuthorId).ToList(),
                BookStoreIds = bookDetails.BookStores_Books.Select(n => n.BookStoreId).ToList(),
                PublisherId = bookDetails.PublisherId,
            };

            var bookDropDownData = await _service.GetNewBookDropdownVals();

            ViewBag.Authors = new SelectList(bookDropDownData.Authors, "Id", "Name");
            ViewBag.Publishers = new SelectList(bookDropDownData.Publishers, "Id", "Name");
            ViewBag.BookStores = new SelectList(bookDropDownData.BookStores, "Id", "Name");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int Id, NewBookVM book)
        {
            if (Id != book.Id)
                return View("NotFound");

            if(!ModelState.IsValid)
            {
                var bookDropDownData = await _service.GetNewBookDropdownVals();

                ViewBag.Authors = new SelectList(bookDropDownData.Authors, "Id", "Name");
                ViewBag.Publishers = new SelectList(bookDropDownData.Publishers, "Id", "Name");
                ViewBag.BookStores = new SelectList(bookDropDownData.BookStores, "Id", "Name");

                return View(book);
            }

            await _service.UpdateBookAsync(book);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var book_to_delete = await _service.GetBookById(Id);
            if(book_to_delete == null)
                return View("NotFound");
            return View(book_to_delete);
        }

        [HttpPost,  ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int Id)
        {
            var book_to_delete = await _service.GetBookById(Id);
            if (book_to_delete == null)
                return View("NotFound");

            await _service.DeleteAsync(Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

E-Books/Controllers/OrdersController.cs
using E_Books.Data.Services;
using E_Books.Data.ViewModels;
using E_Books.Data.Cart;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.IdentityModel.Tokens;

namespace E_Books.Controllers
{
    public class OrdersController : Controller
    {

        private readonly IBooksServices _bookService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        public OrdersController(IBooksServices bookService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _bookService = bookService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddToShoppingCart(int Id)
        {
            var item = await _bookService.GetBookById(Id);

            if (item != null) 
            {
                _shoppingCart.AddItemToCard(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveFromShoppingCart(int Id)
        {
            var item = await _bookService.GetBookById(Id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();

            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            if (!items.IsNullOrEmpty())
            {
                await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
                await _shoppingCart.ClearShoppingCartAsync();
                return View("OrderCompleted");
            }
            return Redirect("~/Books");
        }
    }
}

E-Books/Views/Shared/NotFound.cshtml
<div class="row text-center">
    <div col-md-6 offset-3">
        <h1 class="text-info">404 Not Found!</h1>
        <br />
        <a class="btn btn-outline-success float-center" asp-controller="Books" asp-action="Index">Home Page</a> 
    </div>
</div>

E-Books/Views/Shared/_CreateItem.cshtml
@model String;

@if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div class="text-white" style="position: fixed; right: 25px; bottom: 25px">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success float-end"><i class="bi bi-plus-circle"></i> Add New</a>
    </div>
}

E-Books/Views/Shared/_EditItem.cshtml
@model String;

<div class="text-white" style="position: fixed; right: 25px; bottom: 25px">
    <a asp-controller="@Model" asp-action="Edit" class="btn btn-info float-end"><i class="bi bi-pencil-square"></i> Edit</a>
</div>

E-Books/Views/Shared/_Layout.cshtml
@inject UserManager<AppUser> UserManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - E-Books</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/E_Books.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white" style="justify-content: center; height: 60px">
            <a class="navbar-brand" style=" margin: 10px" asp-controller="Books" asp-action="Index">E-Books<figcaption style="font-size: 15px">For specials</figcaption></a>
            <form class="form-inline my-2 my-lg-0" style="display: inline-flex;" asp-controller="Books" asp-action="Search">
                <input name="searchString" style="height: 48px;" type="text" class="form-control" placeholder="Search for a Book" />
                <button class="btn btn-outline-dark my-2 my-sm-0" style="height: 48px; width: 48px; margin: 5px" type="submit"><i class="bi bi-search"></i></button>
            </form>
            @if (!User.Identity.IsAuthenticated)
            {
                <a asp-controller="Accounts" asp-action="Login" class="btn btn-outline-dark" style="height: 48px; width: 50px;"><i class="bi bi-person"></i><figcaption style="font-size: 10px">Login</figcaption></a>
            }
            else
            {
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="btn btn-outline-dark dropdown-toggle" style="height: 48px; width: 50px;" id="Dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="bi bi-person-circle"></i><figcaption style="font-size: 10px">Profile</figcaption>
                        </a>

                        <div class="dropdown-menu" aria-labelledby="Dropdown">
                            <a class="dropdown-item" asp-controller="Accounts" asp-action="Details">Details</a>
                            <a class="dropdown-item" asp-controller="Orders" asp-action="Index">Orders</a>
                            @if (User.IsInRole("Admin"))
                            {
                                <a class="dropdown-item" asp-controller="Accounts" asp-action="getAllUsers">Users</a>
                            }
                            <form asp-controller="Accounts" asp-action="Logout">
                                <input class="btn btn-outline-danger col-md-12" value="Logout" type="submit"/>
                            </form>
                        </div>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    @await Component.InvokeAsync("ShoppingCartSummary")
                </ul>
            }
        </nav>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3" style="justify-content: center">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Books" asp-action="Index"><i class="bi bi-book"></i> Books</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Authors" asp-action="Index"><span>| </span><i class="bi bi-pencil"></i> Authors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="Publishers" asp-action="Index"><span>| </span><i class="bi bi-buildings"></i> Publishers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" asp-area="" asp-controller="BookStores" asp-action="Index"><span>| </span><i class="bi bi-shop"></i> Bookstores</a>
                </li>
            </ul>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-white" style="background-color: black">
        <div class="links">
            <div class="container">
                <div class="row p-3">
                    <div class="col-md-4">
                        <ul>
                            <h5>About This Project</h5>
                            <li class="text-justify mb-4">
                                Hello my name is Mohammad Bagheri and this is a sample project that I have made with Asp.Net Core MVC
                            </li>
                            <li class="d-flex">
                                <a href="https://github.com/etrupja" title="Github">
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-4 col-6">
                        <div class="col-md-4">
                            <div class="title">
                                <h5 style="display: inline-flex">Contact me</h5>
                            </div>
                            <ul>
                                <li>
                                    <a href="mailto:mohammadbagheriwork@gmail.com" class="text-white">mohammadbagheriwork@gmail.com</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright">
            <div class="container">
                <div class="row">
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>