E-Books/Models/Book.cs
using E_Books.Data.Base;
using E_Books.Data.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace E_Books.Models
{
    public class Book : IEntityBase
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Title is required!")]
        public string Title { get; set; }

        [Display(Name = "Release Date")]
        [Required(ErrorMessage = "Date is required!")]
        public DateTime PublishDate { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        [Required(ErrorMessage = "Price is required!")]
        public decimal Price { get; set; }

        [Required(ErrorMessage = " Summary is required!")]
        public string Summary { get; set; }

        [Required(ErrorMessage = "Cover is required!")]
        [Display(Name = "Cover")]
        public string BookCover { get; set; }

        [Required(ErrorMessage = "Genre is required!")]
        public BookGenre Genre { get; set; }

        //Relations
        // Many to manies
        public List<Author_Book> Authors_Books { get; set; }
        public List<BookStore_Book> BookStores_Books { get; set; }

        //One to many of publisher and book from this side
        public int PublisherId { get; set; }
        [ForeignKey("PublisherId")]
        public Publisher Publisher { get; set; }
    }
}

E-Books/Controllers/AuthorsController.cs
using E_Books.Data.Services;
using E_Books.Models;
using Microsoft.AspNetCore.Mvc;

namespace E_Books.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly IAuthorsServices _service;
        public AuthorsController(IAuthorsServices service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index(int? pageNumber)
        {
            int pageSize = 5;
            var authors = await _service.GetPageAsync(pageNumber ?? 1, pageSize);
            ViewData["TotalPages"] = await _service.TotalPages(pageSize);
            ViewData["PageIndex"] = pageNumber ?? 1;
            return View(authors);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name,Age,Biography,ProfileURL")] Author author)
        {
            if(!ModelState.IsValid)
                return View(author);
            await _service.AddAsync(author);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int Id)
        {
            var author = await _service.GetByIdAsync(Id);
            if (author == null)
                return View("NotFound");
            return View(author);
        }

        public async Task<IActionResult> Edit(int Id)
        {
            var author_for_edit = await _service.GetByIdAsync(Id);
            if (author_for_edit == null)
                return View("NotFound");

            return View(author_for_edit);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int Id, [Bind("Id,Name,Age,Biography,ProfileURL")]Author newAuthor)
        {
            if (!ModelState.IsValid)
                return View(newAuthor);
            await _service.UpdateAsync(Id, newAuthor);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var author_to_delete = await _service.GetByIdAsync(Id);
            if (author_to_delete == null)
                return View("NotFound");
            return View(author_to_delete);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int Id)
        {
            var author_to_delete = await _service.GetByIdAsync(Id);
            if (author_to_delete == null)
                return View("NotFound");

            await _service.DeleteAsync(Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

E-Books/Controllers/BookStoresController.cs
using E_Books.Data.Services;
using E_Books.Models;
using Microsoft.AspNetCore.Mvc;

namespace E_Books.Controllers
{
    public class BookStoresController : Controller
    {
        private readonly IBookStoresServices _service;
        public BookStoresController(IBookStoresServices service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index(int? pageNumber)
        {
            int pageSize = 5;
            var bookStores = await _service.GetPageAsync(pageNumber ?? 1, pageSize);
            ViewData["TotalPages"] = await _service.TotalPages(pageSize);
            ViewData["PageIndex"] = pageNumber ?? 1;
            return View(bookStores);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name,Address,Telephone,LogoURL")] BookStore bookStore)
        {
            if (!ModelState.IsValid)
                return View(bookStore);
            await _service.AddAsync(bookStore);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int Id)
        {
            var bookStore = await _service.GetByIdAsync(Id);
            if (bookStore == null)
                return View("NotFound");
            return View(bookStore);
        }

        public async Task<IActionResult> Edit(int Id)
        {
            var bookStore_for_edit = await _service.GetByIdAsync(Id);
            if (bookStore_for_edit == null)
                return View("NotFound");

            return View(bookStore_for_edit);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int Id, [Bind("Id,Name,Address,Telephone,LogoURL")] BookStore bookStore)
        {
            if (!ModelState.IsValid)
                return View(bookStore);
            await _service.UpdateAsync(Id, bookStore);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var bookStore_to_delete = await _service.GetByIdAsync(Id);
            if (bookStore_to_delete == null)
                return View("NotFound");
            return View(bookStore_to_delete);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int Id)
        {
            var bookStore_to_delete = await _service.GetByIdAsync(Id);
            if (bookStore_to_delete == null)
                return View("NotFound");

            await _service.DeleteAsync(Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

E-Books/Controllers/BooksController.cs
using E_Books.Data.Services;
using E_Books.Data.ViewModels;
using E_Books.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.IdentityModel.Tokens;

namespace E_Books.Controllers
{
    public class BooksController : Controller
    {
        private readonly IBooksServices _service;
        public BooksController(IBooksServices service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index(int? pageNumber)
        {
            int pageSize = 12;
            var books = await _service.GetPageAsync(pageNumber ?? 1, pageSize);
            ViewData["TotalPages"] = await _service.TotalPages(pageSize);
            ViewData["PageIndex"] = pageNumber ?? 1;
            return View(books);
        }

        public async Task<IActionResult> Search(string searchString)
        {
            if (string.IsNullOrEmpty(searchString))
                return RedirectToAction(nameof(Index));
            var result = await _service.SearchAsync(searchString);
            if (result.IsNullOrEmpty())
                return View("NotFound");
            return View(result);
        }

        public async Task<IActionResult> Details(int Id)
        {
            var book = await _service.GetBookById(Id);
            if (book == null)
                return View("NotFound");
            return View(book);
        }

        public async Task<IActionResult> Create()
        {
            var bookDropDownData = await _service.GetNewBookDropdownVals();
            ViewBag.PublisherId = new SelectList(bookDropDownData.Publishers, "Id", "Name");
            ViewBag.AuthorIds = new SelectList(bookDropDownData.Authors, "Id", "Name");
            ViewBag.BookStoreIds = new SelectList(bookDropDownData.BookStores, "Id", "Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(NewBookVM book)
        {
            if (!ModelState.IsValid)
            {
                var bookDropDownData = await _service.GetNewBookDropdownVals();
                ViewBag.PublisherId = new SelectList(bookDropDownData.Publishers, "Id", "Name");
                ViewBag.AuthorIds = new SelectList(bookDropDownData.Authors, "Id", "Name");
                ViewBag.BookStoreIds = new SelectList(bookDropDownData.BookStores, "Id", "Name");
                return View(book);
            }
            await _service.AddNewBook(book);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int Id)
        {
            var bookDetails = await _service.GetBookById(Id);

            if (bookDetails == null)
                return View("NotFound");

            var response = new NewBookVM()
            {
                Id = bookDetails.Id,
                Title = bookDetails.Title,
                PublishDate = bookDetails.PublishDate,
                Price = bookDetails.Price,
                Summary = bookDetails.Summary,
                BookCover = bookDetails.BookCover,
                Genre = bookDetails.Genre,
                AuthorIds = bookDetails.Authors_Books.Select(n => n.AuthorId).ToList(),
                BookStoreIds = bookDetails.BookStores_Books.Select(n => n.BookStoreId).ToList(),
                PublisherId = bookDetails.PublisherId,
            };

            var bookDropDownData = await _service.GetNewBookDropdownVals();

            ViewBag.Authors = new SelectList(bookDropDownData.Authors, "Id", "Name");
            ViewBag.Publishers = new SelectList(bookDropDownData.Publishers, "Id", "Name");
            ViewBag.BookStores = new SelectList(bookDropDownData.BookStores, "Id", "Name");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int Id, NewBookVM book)
        {
            if (Id != book.Id)
                return View("NotFound");

            if(!ModelState.IsValid)
            {
                var bookDropDownData = await _service.GetNewBookDropdownVals();

                ViewBag.Authors = new SelectList(bookDropDownData.Authors, "Id", "Name");
                ViewBag.Publishers = new SelectList(bookDropDownData.Publishers, "Id", "Name");
                ViewBag.BookStores = new SelectList(bookDropDownData.BookStores, "Id", "Name");

                return View(book);
            }

            await _service.UpdateBookAsync(book);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var book_to_delete = await _service.GetBookById(Id);
            if(book_to_delete == null)
                return View("NotFound");
            return View(book_to_delete);
        }

        [HttpPost,  ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int Id)
        {
            var book_to_delete = await _service.GetBookById(Id);
            if (book_to_delete == null)
                return View("NotFound");

            await _service.DeleteAsync(Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

E-Books/Controllers/OrdersController.cs
using E_Books.Data.Services;
using E_Books.Data.ViewModels;
using E_Books.Data.Cart;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.IdentityModel.Tokens;

namespace E_Books.Controllers
{
    public class OrdersController : Controller
    {

        private readonly IBooksServices _bookService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;

        public OrdersController(IBooksServices bookService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _bookService = bookService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<IActionResult> AddToShoppingCart(int Id)
        {
            var item = await _bookService.GetBookById(Id);

            if (item != null) 
            {
                _shoppingCart.AddItemToCard(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveFromShoppingCart(int Id)
        {
            var item = await _bookService.GetBookById(Id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();

            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            if (!items.IsNullOrEmpty())
            {
                await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
                await _shoppingCart.ClearShoppingCartAsync();
                return View("OrderCompleted");
            }
            return Redirect("~/Books");
        }
    }
}

E-Books/Controllers/PublishersController.cs
using E_Books.Data.Services;
using E_Books.Models;
using Microsoft.AspNetCore.Mvc;

namespace E_Books.Controllers
{
    public class PublishersController : Controller
    {
        private readonly IPublishersServices _service;
        public PublishersController(IPublishersServices service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index(int? pageNumber)
        {
            int pageSize = 5;
            var publishers = await _service.GetPageAsync(pageNumber ?? 1, pageSize);
            ViewData["TotalPages"] = await _service.TotalPages(pageSize);
            ViewData["PageIndex"] = pageNumber ?? 1;
            return View(publishers);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name,Description,Address,Email,LogoURL")] Publisher publisher)
        {
            if (!ModelState.IsValid)
                return View(publisher);
            await _service.AddAsync(publisher);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int Id)
        {
            var publisher = await _service.GetByIdAsync(Id);
            if (publisher == null)
                return View("NotFound");
            return View(publisher);
        }

        public async Task<IActionResult> Edit(int Id)
        {
            var publisher_for_edit = await _service.GetByIdAsync(Id);
            if (publisher_for_edit == null)
                return View("NotFound");

            return View(publisher_for_edit);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int Id, [Bind("Id,Name,Description,Address,Email,LogoURL")] Publisher publisher)
        {
            if (!ModelState.IsValid)
                return View(publisher);
            await _service.UpdateAsync(Id, publisher);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var publisher_to_delete = await _service.GetByIdAsync(Id);
            if (publisher_to_delete == null)
                return View("NotFound");
            return View(publisher_to_delete);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int Id)
        {
            var publisher_to_delete = await _service.GetByIdAsync(Id);
            if (publisher_to_delete == null)
                return View("NotFound");

            await _service.DeleteAsync(Id);
            return RedirectToAction(nameof(Index));
        }
    }
}

E-Books/Views/Books/Create.cshtml
@model E_Books.Data.ViewModels.NewBookVM

@{
    ViewData["Title"] = "create a new Book";
}

@if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div class="row">
        <div class="col-md-8 offset-2">
            <p>
                <h4 class="text-center">Create a new book</h4>
            </p>
            <div class="row">
                <div class="col-md-8 offset-2">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger "></div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label asp-for="Title" class="control-label"></label>
                                    <input asp-for="Title" class="form-control" />
                                    <span asp-validation-for="Title" class="text-danger"></span>
                                </div>

                                <div class="form-group">
                                    <label asp-for="PublishDate" class="control-label"></label>
                                    <input asp-for="PublishDate" class="form-control" />
                                    <span asp-validation-for="PublishDate" class="text-danger"></span>
                                </div>

                                <div class="form-group">
                                    <label asp-for="Price" class="control-label"></label>
                                    <input asp-for="Price" class="form-control" />
                                    <span asp-validation-for="Price" class="text-danger"></span>
                                </div>

                                <div class="form-group">
                                    <label asp-for="BookCover" class="control-label"></label>
                                    <input asp-for="BookCover" class="form-control" />
                                    <span asp-validation-for="BookCover" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label asp-for="Genre" class="control-label"></label>
                                    <select asp-for="Genre" class="form-control" asp-items="Html.GetEnumSelectList<E_Books.Data.Enums.BookGenre>()"></select>
                                    <span asp-validation-for="Genre" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="PublisherId" class="control-label"></label>
                                    <select asp-for="PublisherId" class="form-control" asp-items="ViewBag.PublisherId"></select>
                                    <span asp-validation-for="PublisherId" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="AuthorIds" class="control-label"></label>
                                    <select asp-for="AuthorIds" class="form-control" multiple asp-items="ViewBag.AuthorIds"></select>
                                    <span asp-validation-for="AuthorIds" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="BookStoreIds" class="control-label"></label>
                                    <select asp-for="BookStoreIds" class="form-control" multiple asp-items="ViewBag.BookStoreIds"></select>
                                    <span asp-validation-for="BookStoreIds" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label asp-for="Summary" class="control-label"></label>
                                    <textarea asp-for="Summary" class="form-control" multiple></textarea>
                                    <span asp-validation-for="Summary" class="text-danger"></span>
                                </div>



                            </div>
                        </div>
                        <div class="col-md-4 offset-4 text-center">
                            <img width="100%" id="ImageUrlPreview" />
                        </div>

                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-outline-success float-end" />
                            <a class="btn btn-outline-secondary float-first" asp-action="Index">Show all</a>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

    @section Scripts{
    <script>
        $("#BookCover").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
    }
}
else{
    <div>

        <div class="row text-center">
            <div col-md-6 offset-3">
                <h1 class="text-info">404 Not Found!</h1>
                <br />
                <a class="btn btn-outline-success float-center" asp-controller="Books" asp-action="Index">Home Page</a>
            </div>
        </div>
    </div>
}

E-Books/Views/Books/Delete.cshtml
@model Book

@{
    ViewData["Title"] = "Delete a book";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-black">
                        <p class="card-text">
                            <h5 class="card-title">
                                Delete @Model.Title?
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.BookCover" width="100%" alt="@Model.Title">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Summary</p>
                        <p class="card-text">
                            <b>Publisher: </b>
                            <a asp-controller="Publishers" asp-action="Details" asp-route-id="@Model.PublisherId">
                                @Model.Publisher.Name
                            </a>
                        </p>
                        <p class="card-text"><b>Genre: </b>@Model.Genre</p>
                        <p class="card-text"><b>Publish Date: </b>@Model.PublishDate.ToString("dd MMM yy")</p>
                        <p class="card-text" style="display: inline">
                            <b style="max-width: 50px">Available at: </b>
                            @foreach (var bookstore in Model.BookStores_Books)
                            {
                                <div style="display: inline">
                                    <a asp-controller="BookStores" asp-action="Details" asp-route-id="@bookstore.BookStoreId">
                                        @bookstore.BookStore.Name
                                    </a>
                                    <p style="display: inline">-</p>
                                </div>
                            }
                        </p>

                        <p class="card-text">
                            <b>Authors: </b>
                        </p>
                    </div>
                </div>
                <hr />
                <div class="row" style="margin-left: 265px">
                    @foreach (var author in Model.Authors_Books)
                    {
                        <div class="column" style="max-width: 150px">
                            <img class="border-info rounded-circle" src="@author.Author.ProfileURL" style="max-width: 120px" />
                            <br />
                            <div class="text-center">
                                <a asp-controller="Authors" asp-action="Details" asp-route-id="@author.AuthorId">@author.Author.Name</a>
                            </div>
                        </div>
                    }
                </div>
                <div class="col-md-12">
                    <div>
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-end" asp-action="Index">
                                Back to list
                            </a>
                            <form asp-action="Delete" style="max-width: 4px">
                                <input class="btn btn-danger float-start" type="submit" value="Confirm"/>
                            </form>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

E-Books/Views/Books/Details.cshtml
@model Book

@{
    ViewData["Title"] = "Book details";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Title
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.BookCover" width="100%" alt="@Model.Title">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Summary</p>
                        <p class="card-text">
                            <b>Cinema: </b>
                            <a asp-controller="Publishers" asp-action="Details" asp-route-id="@Model.PublisherId">
                                @Model.Publisher.Name
                            </a>
                        </p>
                        <p class="card-text"><b>Genre: </b>@Model.Genre</p>
                        <p class="card-text"><b>Publish Date: </b>@Model.PublishDate.ToString("dd MMM yy")</p>
                        @*Will add status of availability later*@
                        <p class="card-text">
                            <b>Authors: </b>
                            <hr />
                            <div class="row">
                                @foreach (var author in Model.Authors_Books)
                                {
                                    <div class="column text-center">
                                        <img class="border-info rounded-circle" src="@author.Author.ProfileURL" style="max-width: 150px" />
                                        <br />
                                        <a asp-controller="Authors" asp-action="Details" asp-route-id="@author.AuthorId">@author.Author.Name</a>
                                    </div>
                                }
                            </div>
                        </p>

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-first" asp-action="Index">
                                Back to list 
                            </a>
                            <a class="btn btn-success text-white float-end" asp-controller="Orders" asp-action="AddToShoppingCart" asp-route-id="@Model.Id"><i class="bi bi-cart-plus"></i>Add to cart(@Model.Price.ToString("C"))</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>